### ISSUE TITLE
Could not enable the extension

### ISSUE THREAD

**Issue by Tapao-NonSen** [neoncube2/flarum-private-messages#1]
I have just install and I try to enable it but it's not enable and back to disable

**Comment by Sugerland** [comment]
Same

**Comment by ymaxm** [comment]
same

**Comment by neoncube2** [comment]
Hello! :)

Just out of curiosity, how did you find this extension? XD

I've released version 1.1.0, which I believe should fix this issue. If it doesn't, just let me know! :)

**Comment by Tapao-NonSen** [comment]
> Just out of curiosity, how did you find this extension? XD

In extension marketplace

**Comment by neoncube2** [comment]
@Tapao-NonSen Oh, interesting, I didn't realize extensions automatically showed up there :)

**Comment by neoncube2** [comment]
Closing, as I think this should be fixed. If it's not, just let me know! :)
