### ISSUE TITLE
Number of people issue

### ISSUE THREAD

**Issue by ymaxm** [neoncube2/flarum-private-messages#2]
If there are too many people in your chat list (9 or more), this extension will not be able to display the people after them

**Comment by neoncube2** [comment]
Thanks! Working on a fix :)

**Comment by neoncube2** [comment]
I've just released version 1.2.0, which should fix this :)  Thanks again for letting me know about this bug! ^_^

**Comment by neoncube2** [comment]
I had to pull version 1.2.0 because it was letting people view other people's messages, so I'm reopening this.

**Comment by neoncube2** [comment]
I've just released v1.2.1, which should fix this :)
