### ISSUE TITLE
Issue error

### ISSUE THREAD

**Issue by WPFixers** [neoncube2/flarum-private-messages#4]
There is a issue when i send a message Oops! Something went wrong. Refresh the page and try again. left on the bottom what is this error?

**Comment by neoncube2** [comment]
Hi @WPFixers,

Can you find your log file and copy and paste its contents here? If you need help with how to find it, just let me know :)

**Comment by neoncube2** [comment]
Hi @WPFixers, just following up on this :)

**Comment by neoncube2** [comment]
Closing
