### ISSUE TITLE
Messages are doubled

### ISSUE THREAD

**Issue by Pathologic** [neoncube2/flarum-private-messages#9]
![image](https://github.com/user-attachments/assets/26cd9d39-f69e-4e9e-832d-2838cd8fc70b)
To reproduce:
1. Click conversations button
![image](https://github.com/user-attachments/assets/ce5deb2e-93ba-465a-8b37-76e2257b4ccd)
2. Click user name in the list.
3. Close messages window and repeat these actions.

Flarum 1.8.7, Private messages 1.3.0

**Comment by Pathologic** [comment]
https://github.com/neoncube2/flarum-private-messages/blob/main/js/src/forum/components/ConversationView.js#L350 - here is the source of the problem. I've replaced it with:
```
results.forEach((result) => app.cache.messages[this.conversation.id()][result.data.id] = result);
```

Maybe a better solution is possible.

**Comment by neoncube2** [comment]
Thanks, this is great! :D

Sorry, I haven't had a chance to merge this yet, but it's on my radar.

**Comment by Pathologic** [comment]
I've created a PR with my fixes.

**Comment by neoncube2** [comment]
@Pathologic I've just tested this, and it looks great! Thank you very much for the fix and the PR! ^_^
